CREATE TABLE STUDENT(
  STDID INT PRIMARY KEY ,
  FIRSTNAME VARCHAR(25) NOT NULL,
  LASTNAME VARCHAR(25) NOT NULL,
  STDMAIL VARCHAR(30) UNIQUE,
  STDDOB DATE NOT NULL
);
INSERT INTO STUDENT VALUES
(1,'ARJUN','READY','ARJUN@GMAIL.COM','2002-04-21'),
(2,'ISHAA','RAYDU','RAYDU@GMAIL.COM','2007-01-04'),
(3,'SANATH','GOWDA','KUMAR@GMAIL.COM','1996-03-25');

ALTER TABLE STUDENT
ADD (STDADD VARCHAR(40) NOT NULL);

ALTER TABLE STUDENT
RENAME COLUMN STDDOB TO DATEOFBIRTH;

ALTER TABLE STUDENT
DROP COLUMN STDADD;

SELECT * FROM STUDENT;
